FROM rust:1.65-alpine AS builder

WORKDIR /app

#to enable cargo build before adding sources
RUN mkdir src
RUN touch src/main.rs
RUN echo "fn main() {}" > src/main.rs

COPY Cargo.toml .
RUN cargo build --release

RUN rm -r src
RUN rm ./target/release/deps/openvpn_client_rs*
COPY src src
RUN cargo build --release



FROM alpine
RUN apk update && apk add openvpn

WORKDIR /app
COPY --from=builder /app/target/release/openvpn-client-rs ./
ENTRYPOINT ["./openvpn-client-rs"]
