version: "3"

services:
  openvpn_client_rs:
    build: ./
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      PROVIDER: ${PROVIDER}
      SURFSHARK_USER: ${SURFSHARK_USER}
      SURFSHARK_PASSWORD: ${SURFSHARK_PASSWORD}
      PUREVPN_USER: ${PUREVPN_USER}
      PUREVPN_PASSWORD: ${PUREVPN_PASSWORD}
  #enter curl container via "docker exec -it" and check ip via "curl ifconfig.me"
  curl:
    build: curlimages/curl
    depends_on:
      - openvpn_client_rs
    command: tail -f /dev/null
    network_mode: "service:openvpn_client_rs"
